<?php

namespace App\Controller;

use App\Entity\EmployeeAttendance;
use App\Form\AttendanceFileType;
use App\Repository\EmployeeAttendanceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Route("/employee/attendance")
 */
class EmployeeAttendanceController extends AbstractController
{

    /**
     * @Route("/", name="employee_attendance", methods="GET")
     */
    public function index(EmployeeAttendanceRepository $employeeAttendanceRepository): Response
    {
        return $this->render('employee_attendance/index.html.twig', ['attendanceRecs' => $employeeAttendanceRepository->findAll()]);
    }

    /**
     * @Route("/import", name="employee_attendance_import", methods="GET|POST")
     */
    public function import(Request $request): Response
    {
        $attendance = new EmployeeAttendance();
        $form = $this->createForm(AttendanceFileType::class, $attendance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // $file stores the uploaded PDF file
            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $attendance->getFile();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('attandance_directory'),
                $fileName
            );

            // Tosses exception
            $reader = \PHPExcel_IOFactory::createReaderForFile($this->getParameter('attandance_directory') . '/' . $fileName);

            // Need this otherwise dates and such are returned formatted
            /** @noinspection PhpUndefinedMethodInspection */
            $reader->setReadDataOnly(true);

            // Just grab all the rows
            $wb = $reader->load($this->getParameter('attandance_directory') . '/' .$fileName);
            $ws = $wb->getSheet(0);
            $rows = $ws->toArray();

            $em = $this->getDoctrine()->getManager();
            foreach($rows as $i => $row) {
                if($i == 0) {
                    continue;
                }

                $attendanceRec = new EmployeeAttendance();
                $attendanceRec->setEmployeeId($row[0]);
                $attendanceRec->setName($row[1]);
                $attendanceRec->setClockIn(new \DateTime($row[2]));
                $attendanceRec->setClockOut(new \DateTime($row[3]));

                $em->persist($attendanceRec);
                $em->flush();
            }

            // ... persist the $product variable or any other work

            return $this->redirect($this->generateUrl('employee_attendance'));
        }

        return $this->render('employee_attendance/import.html.twig', [
            'controller_name' => 'EmployeeAttendanceController',
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
